In [1]:
# Ensure project root is on sys.path so `src` can be imported from the notebook
from pathlib import Path
import sys
proj_root = Path.cwd().parent
if str(proj_root) not in sys.path:
    sys.path.insert(0, str(proj_root))
print("Added to sys.path:", str(proj_root))

try:
    from src.dataset import GTZANDataset
    print("GTZANDataset available")
except Exception as e:
    print("Import failed:", e)


Added to sys.path: d:\425 Project
GTZANDataset available


In [ ]:
from src.dataset import GTZANDataset

audio_dir = r"D:\gtzan_data\Data\genres_original"
augmented_dir = r"D:\gtzan_data\Data\genres_augmented"

dataset = GTZANDataset(audio_dir, augmented_dir)
X, y = dataset.augment_and_extract()

print("Number of samples:", len(X))
print("First sample shape:", X[0].shape)
print("First 5 labels:", y[:5])


Processed 1/100 files in genre blues
Processed 51/100 files in genre blues
Processed 1/100 files in genre classical
Processed 51/100 files in genre classical
Processed 1/100 files in genre country
Processed 51/100 files in genre country
Processed 1/100 files in genre disco
Processed 51/100 files in genre disco
Processed 1/100 files in genre hiphop
Processed 51/100 files in genre hiphop
Processed 1/100 files in genre jazz
Processed 51/100 files in genre jazz


d:\425 Project\src\dataset.py:32: UserWarning: PySoundFile failed. Trying audioread instead.
  y_audio, sr = librosa.load(filepath, sr=self.sr)
c:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\librosa\core\audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)


Skipping D:\gtzan_data\Data\genres_original\jazz\jazz.00054.wav: 
Processed 1/100 files in genre metal
Processed 51/100 files in genre metal
Processed 1/100 files in genre pop
Processed 51/100 files in genre pop
Processed 1/100 files in genre reggae
Processed 51/100 files in genre reggae
Processed 1/100 files in genre rock
Processed 51/100 files in genre rock
Number of samples: 3996
First sample shape: (1293, 20)
First 5 labels: ['blues' 'blues' 'blues' 'blues' 'blues']


In [ ]:
import os
import numpy as np

# absolute path to the project root (one level up from notebooks/)
project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))

# Path to the original data folder in the project
data_folder = os.path.join(project_root, "data")
os.makedirs(data_folder, exist_ok=True)

# Paths for saving MFCCs and labels
X_save_path = os.path.join(data_folder, "X_mfcc.npy")
y_save_path = os.path.join(data_folder, "y_labels.npy")

# Save
np.save(X_save_path, X, allow_pickle=True)
np.save(y_save_path, y, allow_pickle=True)

print(f"Saved X to {X_save_path}")
print(f"Saved y to {y_save_path}")


Saved X to d:\425 Project\data\X_mfcc.npy
Saved y to d:\425 Project\data\y_labels.npy


In [ ]:
# RUN THIS TO LOAD THE ALREADY SAVED DATA
import numpy as np
import os

project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
data_folder = os.path.join(project_root, "data")

X = np.load(os.path.join(data_folder, "X_mfcc.npy"), allow_pickle=True)
y = np.load(os.path.join(data_folder, "y_labels.npy"), allow_pickle=True)

print(len(X), len(y))


3996 3996


In [2]:
# truncate all MFCC sequences to the minimum length found so that every sample has the same no. of timesteps
# Find the minimum number of timesteps across all samples
min_timesteps = min(mfcc.shape[0] for mfcc in X)
print("Minimum timesteps:", min_timesteps)

# Number of MFCC features
n_mfcc = X[0].shape[1]

# Truncate using list comprehension and stack
X_truncated = np.stack([mfcc[:min_timesteps, :] for mfcc in X])

print("Truncated X shape:", X_truncated.shape)

truncated_path = os.path.join(data_folder, "X_mfcc_truncated.npy")
np.save(truncated_path, X_truncated, allow_pickle=False)

print(f"Truncated MFCCs saved at {truncated_path}")


Minimum timesteps: 1172
Truncated X shape: (3996, 1172, 20)
Truncated MFCCs saved at d:\425 Project\data\X_mfcc_truncated.npy


In [3]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = ""


In [6]:
import sys
print(sys.executable)


c:\Users\Asus\AppData\Local\Programs\Python\Python310\python.exe


In [9]:
import sys, subprocess, traceback
print("sys.executable:", sys.executable)
print("Python version:", sys.version.splitlines()[0])
print("\nChecking installed packages (tensorflow, numpy):")
subprocess.run([sys.executable, "-m", "pip", "show", "tensorflow"], check=False)
subprocess.run([sys.executable, "-m", "pip", "show", "numpy"], check=False)
print("\nFull package list (top 30):")
subprocess.run([sys.executable, "-m", "pip", "list", "--format=columns"], check=False)
print("\nTrying to import TensorFlow (this will show the detailed error):")
try:
    import tensorflow as tf
    print("TensorFlow imported OK:", tf.__version__)
    try:
        print("GPUs found:", tf.config.list_physical_devices("GPU"))
    except Exception as e:
        print("Could not list physical devices:", e)
except Exception:
    traceback.print_exc()

sys.executable: c:\Users\Asus\AppData\Local\Programs\Python\Python310\python.exe
Python version: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]

Checking installed packages (tensorflow, numpy):

Full package list (top 30):

Trying to import TensorFlow (this will show the detailed error):


Traceback (most recent call last):
  File "c:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 73, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Asus\AppData\Local\Temp\ipykernel_3092\2260739510.py", line 11, in <module>
    import tensorflow as tf
  File "c:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\__init__.py", line 40, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow  # pylint: disable=unused-import
  File "c:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 88, in <module>
    raise ImportError(
I

In [10]:
# Install and verify TensorFlow in the current environment (may take several minutes)
import sys, subprocess, traceback
print("Using Python:", sys.executable)

# Show current tensorflow package status
print("\nCurrent tensorflow installation:")
subprocess.run([sys.executable, '-m', 'pip', 'show', 'tensorflow'], check=False)

# Ensure numpy is present and check tensorflow
need_install = False
try:
    import numpy as np
    print("numpy:", np.__version__)
except Exception:
    print("numpy not found — will install")
    need_install = True

try:
    import tensorflow as tf
    print("TensorFlow already installed:", tf.__version__)
except Exception:
    print("TensorFlow not importable — will install or upgrade it")
    need_install = True

if need_install:
    print("\nInstalling/Upgrading pip, numpy, tensorflow, ipykernel — this may take several minutes...")
    cmds = [
        [sys.executable, '-m', 'pip', 'install', '--upgrade', 'pip'],
        [sys.executable, '-m', 'pip', 'install', 'numpy', 'tensorflow', 'ipykernel']
    ]
    for cmd in cmds:
        print('Running:', ' '.join(cmd))
        proc = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
        print(proc.stdout)

print('\nVerifying import now:')
try:
    import tensorflow as tf
    import numpy as np
    print('tensorflow:', tf.__version__)
    print('numpy:', np.__version__)
    try:
        gpus = tf.config.list_physical_devices('GPU')
        print('GPUs:', gpus)
    except Exception as e:
        print('Could not list GPUs:', e)
except Exception:
    print('TensorFlow import failed; traceback below:')
    traceback.print_exc()
    print('\nIf DLL initialisation errors persist, ensure Visual C++ Redistributable (x64) is installed and rebooted')

Using Python: c:\Users\Asus\AppData\Local\Programs\Python\Python310\python.exe

Current tensorflow installation:
numpy: 2.2.3
TensorFlow not importable — will install or upgrade it

Installing/Upgrading pip, numpy, tensorflow, ipykernel — this may take several minutes...
Running: c:\Users\Asus\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip

Running: c:\Users\Asus\AppData\Local\Programs\Python\Python310\python.exe -m pip install numpy tensorflow ipykernel
   ---------------------------------------- 0.0/331.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/331.7 MB ? eta -:--:--
   ---------------------------------------- 1.0/331.7 MB 3.9 MB/s eta 0:01:26
   ---------------------------------------- 1.0/331.7 MB 3.9 MB/s eta 0:01:26
   ---------------------------------------- 1.3/331.7 MB 2.1 MB/s eta 0:02:38
   ---------------------------------------- 1.8/331.7 MB 1.9 MB/s eta 0:02:54
   ---------------------------------------- 2.4/331.7 

Traceback (most recent call last):
  File "c:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 73, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Asus\AppData\Local\Temp\ipykernel_3092\3330014280.py", line 38, in <module>
    import tensorflow as tf
  File "c:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\__init__.py", line 40, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow  # pylint: disable=unused-import
  File "c:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 88, in <module>
    raise ImportError(
I

In [ ]:
import numpy as np
import os

# Load truncated MFCCs

# Correct relative path from notebooks/ folder
X = np.load("../data/X_mfcc_truncated.npy")  # shape: (3996, 1172, 20)
y = np.load("../data/y_labels.npy")          # shape: (3996,)

# Flatten each sample
X_flat = X.reshape(X.shape[0], -1)  # shape: (3996, 1172*20 = 23440)

# Normalize features
X_flat = (X_flat - X_flat.mean()) / (X_flat.std() + 1e-8)

# Save 
os.makedirs("../data", exist_ok=True)  
np.save("../data/X_flat_ready.npy", X_flat)
np.save("../data/y_labels_ready.npy", y)


print("X_flat shape:", X_flat.shape)    # (3996, 23440)
print("y shape:", y.shape)              # (3996,)
print("X_flat mean:", np.mean(X_flat))  
print("X_flat std:", np.std(X_flat))    
print("First 5 labels:",y[:5])


X_flat shape: (3996, 23440)
y shape: (3996,)
X_flat mean: -1.830204592395561e-17
X_flat std: 0.9999999899872776
First 5 labels: ['blues' 'blues' 'blues' 'blues' 'blues']


In [1]:
import numpy as np

# LOAD EASY-TASK VAE LATENTS
Z_vae = np.load("../data/Z_vae.npy")  
print("Shape of Z_vae:", Z_vae.shape)


latent_dim = 32
num_samples = Z_vae.shape[0]

assert Z_vae.shape == (num_samples, latent_dim), \
       f"Z_vae has wrong shape. Expected (*, {latent_dim}), got {Z_vae.shape}"
print("Z_vae has correct latent dimension:", latent_dim)


Shape of Z_vae: (3996, 32)
Z_vae has correct latent dimension: 32


In [2]:
import numpy as np

# LOAD MEDIUM-TASK Conv-VAE LATENTS
Z_conv = np.load("../data/Z_conv_vae.npy")  
print("Shape of Z_conv_vae:", Z_conv.shape)


latent_dim = 32
num_samples = Z_conv.shape[0]

assert Z_conv.shape == (num_samples, latent_dim), \
       f"Z_conv_vae has wrong shape.Expected (*, {latent_dim}), got {Z_conv.shape}"
print("Z_conv_vae has correct latent dimension:", latent_dim)


Shape of Z_conv_vae: (3996, 32)
Z_conv_vae has correct latent dimension: 32


In [4]:
import numpy as np

# Load the one-hot genre vectors
genre_onehot = np.load("../data/genre_onehot.npy")
print("Shape of genre_onehot:", genre_onehot.shape)

# Check that each row sums to 1 (only one genre active)
row_sums = genre_onehot.sum(axis=1)
if np.all(row_sums == 1):
    print("Each row sums to 1")
else:
    print("Some rows do not sum to 1")

# Check that values are only 0 or 1
if np.all(np.logical_or(genre_onehot == 0, genre_onehot == 1)):
    print("Only 0 or 1 values in one-hot")
else:
    print("Non-binary values found")

print("First 5 one-hot vectors:\n", genre_onehot[:5])


Shape of genre_onehot: (3996, 10)
Each row sums to 1
Only 0 or 1 values in one-hot
First 5 one-hot vectors:
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
